import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(const PassApp());

// ---------------------------------------------------------------------------
// Password generation
// ---------------------------------------------------------------------------

const String _lower = 'abcdefghijklmnopqrstuvwxyz';
const String _upper = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
const String _digits = '0123456789';
// Raw string: no escaping needed for '$'.
const String _symbols = r'!@#$%^&*()-_=+:;?';

/// The character groups the user can switch on/off.
/// [label] is what the selector button shows, [chars] is the pool it adds.
enum CharGroup {
  lower('a-z', _lower),
  upper('A-Z', _upper),
  digits('0-9', _digits),
  symbols('#@!', _symbols);

  const CharGroup(this.label, this.chars);
  final String label;
  final String chars;
}

// One CSPRNG instance for the app's lifetime (backed by the OS entropy source).
final Random _rng = Random.secure();

/// Generates one password of [length] characters using only [groups].
/// Guarantees at least one character from every selected group.
String generatePassword(int length, Set<CharGroup> groups) {
  assert(groups.isNotEmpty, 'At least one character group is required');
  assert(length >= groups.length, 'Length must fit one char per group');

  String pick(String s) => s[_rng.nextInt(s.length)];

  // Combined pool built only from the selected groups.
  final pool = groups.map((g) => g.chars).join();

  // 1) One guaranteed character from each selected group.
  final chars = <String>[for (final g in groups) pick(g.chars)];

  // 2) Fill the remainder from the combined pool.
  while (chars.length < length) {
    chars.add(pick(pool));
  }

  // 3) Shuffle with the secure RNG so guaranteed chars aren't always first.
  chars.shuffle(_rng);
  return chars.join();
}

// ---------------------------------------------------------------------------
// Theme: strict black & white
//   background = white, foreground/controls = black, text on black = white
// ---------------------------------------------------------------------------

const Color _black = Colors.black;
const Color _white = Colors.white;

// UI font for the whole app. Must match the family name declared in
// pubspec.yaml (see note below). Set to null to use the platform default.

// Font for the password itself. Monospace keeps characters like l/1/I/0/O
// distinguishable, which matters for a password display.
const String _mono = 'monospace';

ThemeData _buildTheme() {
  // Explicit scheme so Material 3 never injects tinted/seeded colors.
  const scheme = ColorScheme.light(
    primary: _black,
    onPrimary: _white,
    secondary: _black,
    onSecondary: _white,
    surface: _white,
    onSurface: _black,
    error: _black,
    onError: _white,
    outline: _black,
  );

  // Shared button shape.
  final buttonShape = RoundedRectangleBorder(
    borderRadius: BorderRadius.circular(12),
  );

  // Shared button label style. fontFamily set explicitly because ButtonStyle
  // text styles don't reliably inherit ThemeData.fontFamily.
  const buttonText = TextStyle(
    fontFamily: _mono,
    fontSize: 14,
    fontWeight: FontWeight.w600,
  );

  final base = ThemeData(
    useMaterial3: true,
    colorScheme: scheme,

    // Global font. Applies to every text style generated by the theme.
    fontFamily: _mono,

    scaffoldBackgroundColor: _white,
    canvasColor: _white,

    // Remove ink effects for a flat, crisp look.
    splashFactory: NoSplash.splashFactory,
    splashColor: Colors.transparent,
    highlightColor: Colors.transparent,
    hoverColor: Colors.transparent,

    appBarTheme: const AppBarTheme(
      backgroundColor: _white,
      foregroundColor: _black,
      surfaceTintColor: Colors.transparent, // no M3 tint on scroll
      elevation: 0,
      scrolledUnderElevation: 0,
      centerTitle: false,
      titleTextStyle: TextStyle(
        fontFamily: _mono,
        color: _black,
        fontSize: 20,
        fontWeight: FontWeight.w700,
      ),
      // Dark icons on the white status/navigation bars.
      systemOverlayStyle: SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness: Brightness.dark,
        statusBarBrightness: Brightness.light, // iOS
        systemNavigationBarColor: _white,
        systemNavigationBarIconBrightness: Brightness.dark,
      ),
    ),

    // Primary action: black fill, white text.
    filledButtonTheme: FilledButtonThemeData(
      style: FilledButton.styleFrom(
        backgroundColor: const Color.fromARGB(255, 55, 158, 255),
        foregroundColor: _white,
        minimumSize: const Size.fromHeight(46),
        shape: buttonShape,
        textStyle: buttonText,
      ),
    ),

    // Secondary action: white fill, black text + black border.
    outlinedButtonTheme: OutlinedButtonThemeData(
      style: OutlinedButton.styleFrom(
        backgroundColor: _white,
        foregroundColor: _black,
        minimumSize: const Size.fromHeight(36),
        side: const BorderSide(
          color: Color.fromARGB(255, 173, 215, 255),
          width: 1.5,
        ),
        shape: buttonShape,
        textStyle: buttonText,
      ),
    ),

    // Length selector: selected = black/white text, unselected = white/black.
    segmentedButtonTheme: SegmentedButtonThemeData(
      style: SegmentedButton.styleFrom(
        backgroundColor: _white,
        foregroundColor: const Color.fromARGB(255, 0, 0, 0),
        selectedBackgroundColor: const Color.fromARGB(255, 21, 142, 255),
        selectedForegroundColor: _white,
        side: const BorderSide(color: _black, width: 1.5),
        shape: buttonShape,
        textStyle: buttonText,
      ),
    ),

    // Toast: black bar, white text.
    snackBarTheme: SnackBarThemeData(
      backgroundColor: _black,
      contentTextStyle: const TextStyle(
        fontFamily: _mono,
        fontSize: 16,
        color: _white,
      ),
      behavior: SnackBarBehavior.floating,
      shape: buttonShape,
    ),

    // Cursor + text selection in monochrome.
    textSelectionTheme: const TextSelectionThemeData(
      cursorColor: _black,
      selectionHandleColor: Color.fromARGB(255, 255, 203, 73),
      selectionColor: Color.fromARGB(
        154,
        255,
        171,
        74,
      ), // black @ 20% so text stays readable
    ),
  );

  // Force every text style (body, title, label...) to black on white and to
  // the app font, so no widget falls back to a default color or family.
  return base.copyWith(
    textTheme: base.textTheme.apply(
      fontFamily: _mono,
      bodyColor: _black,
      displayColor: _black,
    ),
  );
}

// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------

class PassApp extends StatelessWidget {
  const PassApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'OffPass',
      theme: _buildTheme(),
      // Single theme app: no dark variant, never follow system dark mode.
      themeMode: ThemeMode.light,
      home: const HomePage(),
    );
  }
}

// ---------------------------------------------------------------------------
// Home page
// ---------------------------------------------------------------------------

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  static const List<int> _lengths = [8, 12, 16, 36, 64, 100, 256];

  int _length = 16;

  // Character groups currently enabled. Starts with all four on.
  Set<CharGroup> _groups = CharGroup.values.toSet();

  late String _password = generatePassword(_length, _groups);

  /// Produces a fresh password with the current length and groups.
  void _generate() =>
      setState(() => _password = generatePassword(_length, _groups));

  /// Changes the length and regenerates in a single rebuild.
  void _onLengthChanged(Set<int> selection) {
    setState(() {
      _length = selection.first;
      _password = generatePassword(_length, _groups);
    });
  }

  /// Changes the enabled character groups and regenerates in a single rebuild.
  /// SegmentedButton never reports an empty set (emptySelectionAllowed is
  /// false), so there is always at least one group to generate from.
  void _onGroupsChanged(Set<CharGroup> selection) {
    setState(() {
      _groups = selection;
      _password = generatePassword(_length, _groups);
    });
  }

  Future<void> _copy() async {
    await Clipboard.setData(ClipboardData(text: _password));
    // Async gap: the widget may have been disposed while awaiting.
    if (!mounted) return;
    ScaffoldMessenger.of(context)
      ..hideCurrentSnackBar() // avoid stacking toasts on rapid taps
      ..showSnackBar(
        SnackBar(
          content: Text(
            'Copied: $_password',
            style: TextStyle(color: const Color.fromARGB(255, 60, 60, 60)),
          ),
          duration: const Duration(seconds: 2),
          // behavior:,
          backgroundColor: const Color.fromARGB(255, 247, 247, 247),
        ),
      );
  }

  /// Toggles one group on/off. Ignores the tap if it would leave
  /// no groups selected, so the generator always has a pool.
  void _toggleGroup(CharGroup g) {
    final next = {..._groups};
    if (!next.remove(g)) next.add(g);
    if (next.isEmpty) return;
    _onGroupsChanged(next);
  }

  /// Builds the password as spans with an invisible zero-width space after
  /// every character, so the line can wrap anywhere instead of only after
  /// '-', '?', '!', ';' etc. The zero-width space gets letterSpacing 0 so
  /// it doesn't add extra gap between characters.
  TextSpan _passwordSpan(String password, TextStyle style) {
    return TextSpan(
      style: style,
      children: [
        for (final c in password.split('')) ...[
          TextSpan(text: c),
          const TextSpan(text: '\u200B', style: TextStyle(letterSpacing: 0)),
        ],
      ],
    );
  }

  // Whether the README section is expanded. Collapsed by default.
  bool _readmeOpen = false;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: const Color.fromARGB(255, 255, 255, 255),
        title: const Text('OffPass Generator'),
      ),
      // SafeArea respects gesture bars / cutouts; scroll view prevents
      // overflow on small screens, landscape, or large font scaling.
      body: SafeArea(
        child: SingleChildScrollView(
          physics: const BouncingScrollPhysics(),
          padding: const EdgeInsets.all(20),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const SizedBox(height: 10),

              // Password display card.
              Container(
                padding: const EdgeInsets.symmetric(
                  horizontal: 12,
                  vertical: 6,
                ),
                decoration: BoxDecoration(
                  color: _white,
                  border: Border.all(
                    color: const Color.fromARGB(255, 147, 216, 255),
                    width: 0.7,
                  ),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: SelectableText.rich(
                  _passwordSpan(
                    _password,
                    // Only widget that overrides the app font on purpose.
                    const TextStyle(
                      fontFamily: _mono,
                      fontSize: 18,
                      color: _black,
                      letterSpacing: 2,
                    ),
                  ),
                  scrollPhysics: const BouncingScrollPhysics(),
                  textAlign: TextAlign.start,
                  textScaler: const TextScaler.linear(0.9),
                ),
              ),
              const SizedBox(height: 20),

              // Length selector.
              // Length selector: separate rounded buttons with a gap between them.
              // Same colors as segmentedButtonTheme (selected = blue/white text,
              // unselected = white/black text + black border).
              Row(
                children: [
                  for (var i = 0; i < _lengths.length; i++) ...[
                    if (i > 0) const SizedBox(width: 8), // gap between buttons
                    Expanded(
                      child: Semantics(
                        selected: _lengths[i] == _length,
                        child: OutlinedButton(
                          // Tapping the active length does nothing, same as the
                          // old SegmentedButton.
                          onPressed: _lengths[i] == _length
                              ? null
                              : () => _onLengthChanged({_lengths[i]}),
                          style: OutlinedButton.styleFrom(
                            // Disabled colors are set too, because the active button
                            // is disabled (onPressed: null) and would turn grey.
                            backgroundColor: _lengths[i] == _length
                                ? const Color.fromARGB(255, 21, 142, 255)
                                : _white,
                            disabledBackgroundColor: const Color.fromARGB(
                              255,
                              21,
                              142,
                              255,
                            ),
                            foregroundColor: _black,
                            disabledForegroundColor: _white,
                            minimumSize: const Size(0, 22),
                            padding: EdgeInsets.zero,
                            side: BorderSide(
                              color: _lengths[i] == _length
                                  ? const Color.fromARGB(255, 21, 142, 255)
                                  : _black,
                              width: 0.7,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(
                                10,
                              ), // change radius here
                            ),
                          ),
                          child: Text('${_lengths[i]}'),
                        ),
                      ),
                    ),
                  ],
                ],
              ),
              const SizedBox(height: 10),

              // Character group selector (multi-select, same theme as above).
              // At least one group must stay selected.
              // Character group selector: separate rounded buttons with a gap.
              // Multi-select: selected = blue/white text, unselected = white/black text.
              // At least one group always stays on (enforced in _toggleGroup).
              Row(
                children: [
                  for (var i = 0; i < CharGroup.values.length; i++) ...[
                    if (i > 0) const SizedBox(width: 8), // gap between buttons
                    Expanded(
                      child: Semantics(
                        selected: _groups.contains(CharGroup.values[i]),
                        child: OutlinedButton(
                          onPressed: () => _toggleGroup(CharGroup.values[i]),
                          style: OutlinedButton.styleFrom(
                            backgroundColor:
                                _groups.contains(CharGroup.values[i])
                                ? const Color.fromARGB(255, 21, 142, 255)
                                : _white,
                            foregroundColor:
                                _groups.contains(CharGroup.values[i])
                                ? _white
                                : _black,
                            minimumSize: const Size(0, 22), // taller = roomier
                            padding: const EdgeInsets.symmetric(horizontal: 12),
                            side: BorderSide(
                              color: _groups.contains(CharGroup.values[i])
                                  ? const Color.fromARGB(255, 21, 142, 255)
                                  : _black,
                              width: 0.6,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                          child: Text(CharGroup.values[i].label),
                        ),
                      ),
                    ),
                  ],
                ],
              ),
              const SizedBox(height: 10),

              // Styling comes entirely from the theme.
              FilledButton(onPressed: _generate, child: const Text('Generate')),
              const SizedBox(height: 10),
              OutlinedButton.icon(
                onPressed: _copy,
                icon: const Icon(Icons.copy),
                label: const Text('Copy'),
              ),
              const SizedBox(height: 20),

              // README: collapsed shows only the label, tap to expand/collapse.
              // Keep every claim in the text true of the code above.
              InkWell(
                onTap: () => setState(() => _readmeOpen = !_readmeOpen),
                borderRadius: BorderRadius.circular(10),
                child: Padding(
                  padding: const EdgeInsets.symmetric(vertical: 8),
                  child: Row(
                    children: [
                      const Text(
                        'README',
                        style: TextStyle(
                          fontSize: 14,
                          fontWeight: FontWeight.w600,
                          color: _black,
                        ),
                      ),
                      const SizedBox(width: 4),
                      // Arrow flips when open.
                      AnimatedRotation(
                        turns: _readmeOpen ? 0.5 : 0,
                        duration: const Duration(milliseconds: 200),
                        child: const Icon(
                          Icons.keyboard_arrow_down,
                          size: 20,
                          color: _black,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              // AnimatedSize smoothly grows/shrinks the area as the text appears.
              AnimatedSize(
                duration: const Duration(milliseconds: 200),
                curve: Curves.easeInOut,
                alignment: Alignment.topCenter,
                child: _readmeOpen
                    ? const Padding(
                        padding: EdgeInsets.only(top: 8),
                        child: Text(
                          'Passwords are generated on your device using your phone\'s '
                          'cryptographically secure random number generator, the same source '
                          'the operating system uses for encryption keys. Choose which '
                          'character types to include: every password contains at least '
                          'one character from each type you select, mixed in a '
                          'random order so there is no predictable pattern. Nothing is saved '
                          'or sent anywhere. Longer passwords with more character types are '
                          'stronger, so use 16 characters or more where you can.',
                          textAlign: TextAlign.start,
                          style: TextStyle(
                            fontSize: 14,
                            wordSpacing: 3,
                            letterSpacing: -0.6,
                            height: 1.5,
                            color: Color.fromARGB(255, 40, 40, 40),
                          ),
                        ),
                      )
                    // Empty box keeps full width while collapsed.
                    : const SizedBox(width: double.infinity),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
